- name: configure mysqlserver
  hosts: mysql
  become: true
  tasks:
   - name: install mysql
     ansible.builtin.package:
         name: mysql-server
         state: installed
   - name : enable mysql
     ansible.builtin.service:
          name: mysqld
          state: started
          enabled: yes

    - name: connect to mysqlserver
      community.mysql.mysql_info:
           login_user: root
           login_password: ExpenseApp@1
           login_host: mysql.kittudevops.shop 
      register: mysql_info

    - name: print output
      ansible.builtin.debug:
       msg: "mysql information :{{mysql_info}}"    
