- name: configure mysqlserver
  hosts: mysql
  become: true
  tasks:
   - name: install mysql
     ansible.builtin.package:
         name: mysql
         state: installed
   - name : enable mysql
     ansible.builtin.service:
          name: mysqld
          state: started
          enabled: yes
   
           